server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: incident-service-cases
          uri: lb://incident-service
          predicates:
            - Path=/api/v1/cases/**
          filters:
            - StripPrefix=0
        - id: incident-service-lookups
          uri: lb://incident-service
          predicates:
            - Path=/api/v1/lookups/**
          filters:
            - StripPrefix=0
        - id: incident-service-incidents
          uri: lb://incident-service
          predicates:
            - Path=/api/v1/incidents/**
          filters:
            - StripPrefix=0
        - id: financial-service
          uri: lb://financial-service
          predicates:
            - Path=/api/v1/financial/**
          filters:
            - StripPrefix=0
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - StripPrefix=0
        - id: conversational-ai-ws
          uri: lb:ws://conversational-ai-service
          predicates:
            - Path=/ws/chat/**
          filters:
            - StripPrefix=0
        - id: conversational-ai-http
          uri: lb://conversational-ai-service
          predicates:
            - Path=/api/v1/chat/**
          filters:
            - StripPrefix=0
        - id: graph-service
          uri: lb://graph-service
          predicates:
            - Path=/api/v1/graph/**
          filters:
            - StripPrefix=0
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/v1/search/**
          filters:
            - StripPrefix=0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
