server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discovery-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

eureka:
  instance:
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: discovery-service
  tracing:
    enabled: false
    distribution:
      percentiles-histogram:
        http.server.requests: true
